version: "3"

services: 
  db:
    image: postgres    
  web:
    container_name: web
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./timber_base:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  ng:
    container_name: ng
    build: angular
    ports:
      - "8080:8000"