# Generated by Django 2.1.4 on 2019-12-13 00:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=12)),
                ('created_on', models.DateField(default=datetime.date.today)),
            ],
            options={
                'db_table': 'customer',
                'ordering': ['id'],
            },
        ),
    ]
